"""empty message

Revision ID: 29637235acdd
Revises: f20a466b3560
Create Date: 2023-01-26 17:35:16.496750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29637235acdd'
down_revision = 'f20a466b3560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_actors', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('genre')
        batch_op.drop_column('budget')
        batch_op.drop_column('main_actors')

    # ### end Alembic commands ###
