from selenium.webdriver.common.by import By
import pytest
import time
from BaseClass import BaseClass
import logging as logger
@pytest.mark.usefixtures("setup")
@pytest.mark.security
class TestSecurity(BaseClass):
    def test_ending_of_file(self, setup):
        logger = self.getLogger()
        setup.get("http://127.0.0.1:5000/")
        time.sleep(3)
        setup.find_element(By.XPATH, "//button[text()='Add Movie']").click()
        setup.find_element(By.XPATH, "//input[@name='filename']").send_keys("C:/Users/roaya/OneDrive/Desktop/Testing file.txt")
        setup.find_element(By.XPATH, "//input[@name='movie_title']").send_keys("TEST")
        setup.find_element(By.XPATH, "//textarea[@name='description']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='director']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='release_year']").send_keys("2023")
        setup.find_element(By.XPATH, "//textarea[@name='main_actors']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='proper_age']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='budget']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='genre']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='duration']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='video']").send_keys("TEST")
        # setup.get_screenshot_as_file('screenshots/security/errorINFO.jpg')
        time.sleep(3)
        setup.find_element(By.XPATH, "//button[text()='Add Movie']").click()
        assert setup.find_element(By.XPATH, "//p[@class='errormsg']").text == "UnboundLocalError: cannot access local variable 'final_name' where it is not associated with a value"
        # setup.get_screenshot_as_file('screenshots/security/errorMSG.jpg')
        logger.info("Security test case 1 - Passed!")

    def test_modify_photo(self, setup):
        logger = self.getLogger()
        setup.get("http://127.0.0.1:5000/")
        setup.find_element(By.XPATH, "//button[text()='Add Movie']").click()
        setup.find_element(By.XPATH, "//input[@name='filename']").send_keys("C:/Users/roaya/OneDrive/Desktop/nostringsattached.jpg")
        setup.find_element(By.XPATH, "//input[@name='movie_title']").send_keys("No Strings Attached")
        setup.find_element(By.XPATH, "//textarea[@name='description']").send_keys("Starring Natalie Portman and Ashton Kutcher, the film is about two friends who decide to make a pact to have a 'no strings attached' relationship, without falling in love with each other.")
        setup.find_element(By.XPATH, "//input[@name='director']").send_keys("Ivan Reitman")
        setup.find_element(By.XPATH, "//input[@name='release_year']").send_keys("2011")
        setup.find_element(By.XPATH, "//textarea[@name='main_actors']").send_keys("Natalie Portman, Ashton Kutcher, Greta Gerwig, Kevin kline")
        setup.find_element(By.XPATH, "//input[@name='proper_age']").send_keys("+17")
        setup.find_element(By.XPATH, "//input[@name='budget']").send_keys("$25 Million")
        setup.find_element(By.XPATH, "//input[@name='genre']").send_keys("Romance, Comedy")
        setup.find_element(By.XPATH, "//input[@name='duration']").send_keys("1h 50m")
        setup.find_element(By.XPATH, "//input[@name='video']").send_keys("https://www.youtube.com/embed/v=XGmsRMvQ2AM")
        setup.find_element(By.XPATH, "//button[text()='Add Movie']").click()
        time.sleep(2)
        setup.find_element(By.XPATH, "//div/a[9]/img[1]").click()
        setup.execute_script("window.scrollBy(0, document.body.scrollHeight);")
        time.sleep(2)
        setup.find_element(By.XPATH, "//button[normalize-space()='Update Movie']").click()
        setup.find_element(By.XPATH, "//input[@name='filename']").send_keys("C:/Users/roaya/OneDrive/Desktop/MammaMia.jpg")
        setup.find_element(By.XPATH, "//button[text()='Update Movie']").click()
        time.sleep(2)
        setup.find_element(By.XPATH, "//img[@src='../static/logo.jpg']").click()
        setup.find_element(By.XPATH, "//div/a[12]/img[1]").click()
        time.sleep(2)
        setup.find_element(By.XPATH, "//button[normalize-space()='Delete Movie']").click()
        setup.find_element(By.XPATH, "//img[@src='../static/logo.jpg']").click()
        assert setup.find_element(By.XPATH, "//div/a[9]/img[1]").is_displayed()
        logger.info("Security test case 2 - Passed!")

    def test_watchlist_twice(self, setup):
        logger = self.getLogger()
        setup.get("http://127.0.0.1:5000/")
        setup.find_element(By.XPATH, "//img[@src='/display/goodwillhunting.jpg']").click()
        setup.execute_script("window.scrollBy(0, document.body.scrollHeight);")
        time.sleep(2)
        setup.find_element(By.XPATH, "//button[text()='+MyList']").click()
        setup.find_element(By.XPATH, "//img[@src='../static/logo.jpg']").click()
        setup.find_element(By.XPATH, "//button[text()='My Watchlist']").click()
        time.sleep(5)
        movies_before = setup.find_elements(By.XPATH, "//div//img")
        # setup.get_screenshot_as_file('screenshots/functional/MovieOnWatchlist.jpg')
        setup.find_element(By.XPATH, "//img[@src='../static/logo.jpg']").click()
        setup.find_element(By.XPATH, "//img[@src='/display/goodwillhunting.jpg']").click()
        setup.execute_script("window.scrollBy(0, document.body.scrollHeight);")
        time.sleep(2)
        setup.find_element(By.XPATH, "//button[text()='+MyList']").click()
        setup.find_element(By.XPATH, "//img[@src='../static/logo.jpg']").click()
        setup.find_element(By.XPATH, "//button[text()='My Watchlist']").click()
        time.sleep(5)
        movies_after = setup.find_elements(By.XPATH, "//div//img")
        assert len(movies_before) == len(movies_after)
        logger.info("Security test case 3 - Passed!")

    def test_release_year_input(self, setup):
        logger = self.getLogger()
        setup.get("http://127.0.0.1:5000/")
        setup.find_element(By.XPATH, "//button[text()='Add Movie']").click()
        setup.find_element(By.XPATH, "//input[@name='filename']").send_keys("C:/Users/roaya/OneDrive/Desktop/nostringsattached.jpg")
        setup.find_element(By.XPATH, "//input[@name='movie_title']").send_keys("TEST")
        setup.find_element(By.XPATH, "//textarea[@name='description']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='director']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='release_year']").send_keys("TEST")
        setup.find_element(By.XPATH, "//textarea[@name='main_actors']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='proper_age']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='budget']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='genre']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='duration']").send_keys("TEST")
        setup.find_element(By.XPATH, "//input[@name='video']").send_keys("TEST")
        setup.find_element(By.XPATH, "//button[text()='Add Movie']").click()
        time.sleep(2)
        # setup.get_screenshot_as_file('screenshots/security/warningMSG.jpg')
        logger.info("Security test case 4 - Passed!")

    def test_link_starts_with_https(self, setup):
        logger = self.getLogger()
        setup.get("http://127.0.0.1:5000/")
        assert setup.current_url.startswith("http://")
        logger.info("Security test case 5 - Passed!")
